#   Copyright (C) 2000-2026 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# Various utilities for scanning ltrans tree dump output, used by gcc-dg.exp and
# g++-dg.exp.

load_lib scandump.exp

# Define scan-ltrans-{tree,rtl}-dump{,-not,-dem,-dem-not}.  These are LTO
# variants of the corresponding functions without -ltrans in the name.
foreach ir { tree rtl } {
    foreach modifier { {} -not -dem -dem-not } {
	eval [string map [list @NAME@ scan-ltrans-$ir-dump$modifier \
			       @SCAN@ scan-dump$modifier \
			       @TYPE@ ltrans-$ir \
			       @SUFFIX@ [string index $ir 0]] {
	    proc @NAME@ { args } {
		if { [llength $args] < 2 } {
		    error "@NAME@: too few arguments"
		    return
		}
		if { [llength $args] > 3 } {
		    error "@NAME@: too many arguments"
		    return
		}
		if { [llength $args] >= 3 } {
		    @SCAN@ @TYPE@ [lindex $args 0] \
			"\[0-9\]\[0-9\]\[0-9\]@SUFFIX@.[lindex $args 1]" \
			".ltrans0.ltrans" \
			[lindex $args 2]
		} else {
		    @SCAN@ @TYPE@ [lindex $args 0] \
			"\[0-9\]\[0-9\]\[0-9\]@SUFFIX@.[lindex $args 1]" \
			".ltrans0.ltrans"
		}
	    }
	}]
    }
}

# Define scan-ltrans-{tree,rtl}-dump-times.  These are LTO variants of the
# corresponding functions without -ltrans in the name.
foreach ir { tree rtl } {
    eval [string map [list @NAME@ scan-ltrans-$ir-dump-times \
			   @TYPE@ ltrans-$ir \
			   @SUFFIX@ [string index $ir 0]] {
	proc @NAME@ { args } {
	    if { [llength $args] < 3 } {
		error "@NAME@: too few arguments"
		return
	    }
	    if { [llength $args] > 4 } {
		error "@NAME@: too many arguments"
		return
	    }
	    if { [llength $args] >= 4 } {
		scan-dump-times "@TYPE@" [lindex $args 0] [lindex $args 1] \
		    "\[0-9\]\[0-9\]\[0-9\]@SUFFIX@.[lindex $args 2]" \
		    ".ltrans0.ltrans" [lindex $args 3]
	    } else {
		scan-dump-times "@TYPE@" [lindex $args 0] [lindex $args 1] \
		    "\[0-9\]\[0-9\]\[0-9\]@SUFFIX@.[lindex $args 2]" \
		    ".ltrans0.ltrans"
	    }
	}
    }]
}

# Scan LTRANS assembly output (.ltrans*.s files).

proc scan-ltrans-assembler { args } {
    if { [llength $args] < 1 } {
	error "scan-ltrans-assembler: too few arguments"
	return
    }
    if { [llength $args] > 2 } {
	error "scan-ltrans-assembler: too many arguments"
	return
    }
    if { [llength $args] >= 2 } {
	switch [dg-process-target [lindex $args 1]] {
	    "S" { }
	    "N" { return }
	    "F" { setup_xfail "*-*-*" }
	    "P" { }
	}
    }

    set testcase [testname-for-summary]
    set pattern [lindex $args 0]
    set pp_pattern [make_pattern_printable $pattern]
    set testname [lindex $testcase 0]
    set basename [file rootname $testname]
    set output_files [dg_glob_remote "${basename}.ltrans*.s"]

    if { $output_files == "" } {
       verbose -log "$testcase: no ${basename}.ltrans*.s files found"
       unresolved "$testcase scan-ltrans-assembler $pp_pattern"
       return
    }

    set total_matches 0
    foreach file $output_files {
       set fd [open $file r]
       set text [read $fd]
       close $fd
       set matches [regexp -all -- $pattern $text]
       set total_matches [expr $total_matches + $matches]
    }

    if { $total_matches > 0 } {
       pass "$testcase scan-ltrans-assembler $pp_pattern"
    } else {
       fail "$testcase scan-ltrans-assembler $pp_pattern"
    }
}
set_required_options_for scan-ltrans-assembler

proc scan-ltrans-assembler-times { args } {
    if { [llength $args] < 2 } {
	error "scan-ltrans-assembler-times: too few arguments"
	return
    }
    if { [llength $args] > 3 } {
	error "scan-ltrans-assembler-times: too many arguments"
	return
    }
    if { [llength $args] >= 3 } {
	switch [dg-process-target [lindex $args 2]] {
	    "S" { }
	    "N" { return }
	    "F" { setup_xfail "*-*-*" }
	    "P" { }
	}
    }

    set testcase [testname-for-summary]
    set pattern [lindex $args 0]
    set times [lindex $args 1]
    set pp_pattern [make_pattern_printable $pattern]
    set testname [lindex $testcase 0]
    set basename [file rootname $testname]
    set output_files [dg_glob_remote "${basename}.ltrans*.s"]
    
    if { $output_files == "" } {
	verbose -log "$testcase: no ${basename}.ltrans*.s files found"
	unresolved "$testcase scan-ltrans-assembler-times $pp_pattern $times"
	return
    }
    
    set total_matches 0
    foreach file $output_files {
	set fd [open $file r]
	set text [read $fd]
	close $fd
	set matches [regexp -all -- $pattern $text]
	set total_matches [expr $total_matches + $matches]
    }
    
    if { $total_matches == $times } {
	pass "$testcase scan-ltrans-assembler-times $pp_pattern $times"
    } else {
	verbose -log "$testcase: $pp_pattern found $total_matches times"
	fail "$testcase scan-ltrans-assembler-times $pp_pattern $times"
    }
}
set_required_options_for scan-ltrans-assembler-times
