# Copyright (C) 2024-2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# GCC testsuite that uses the `dg.exp' driver.

# Exit immediately if this isn't a RISC-V target.
if ![istarget riscv*-*-*] then {
  return
}

# Load support procs.
load_lib gcc-dg.exp

global DEFAULT_CFLAGS
if ![info exists DEFAULT_CFLAGS] then {
    set DEFAULT_CFLAGS " -ansi -pedantic-errors"
}

# Initialize `dg'.
dg-init

# Main loop.
#dg-runtest [lsort [glob -nocomplain $srcdir/$subdir/*.\[cS\]]] \
#        "" $DEFAULT_CFLAGS

restore_ld_library_path_env_vars

set status [remote_exec host "$HOSTCXX $HOSTCFLAGS -std=c++11 -m32 -fPIC -shared -I \
/slowfs/us01dwt2p351/nsim/bleeding-edge/latest/Linux/nSIM/inc $srcdir/$subdir/nsim_apex32.cpp \
-o $srcdir/$subdir/../dll/nsim_apex32.so"]

set status [lindex $status 0]

set_ld_library_path_env_vars

foreach opt {
  {-O2}
} {
  dg-runtest [lsort [glob -nocomplain $srcdir/$subdir/*.\[cS\]]] \
    "$opt" ""
}

# All done.
dg-finish
