# Copyright (C) 2024-2025 Free Software Foundation, Inc.

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with GCC; see the file COPYING3.  If not see
# <http://www.gnu.org/licenses/>.

# GCC testsuite for RISC-V APEX custom instructions.

# Exit immediately if this isn't a RISC-V target.
if ![istarget riscv*-*-*] then {
  return
}

# Load support libraries.
load_lib gcc-dg.exp
load_lib standard.exp
load_lib lto.exp
load_lib scanltrans.exp

# Run regular single-file tests.
dg-init
set tests [lsort [glob -nocomplain $srcdir/$subdir/*.\[cS\]]]
set non_lto_tests [list]
foreach test $tests {
    if {![string match "*arcv-apex-lto-*" $test]} {
        lappend non_lto_tests $test
    }
}
dg-runtest $non_lto_tests "" ""
dg-finish

# Run multi-file LTO tests if supported.
if [check_effective_target_lto] {
    lto_init no-mathlib

    foreach src [lsort [find $srcdir/$subdir arcv-apex-lto-*_0.c]] {
        if [runtest_file_p $runtests $src] {
            lto-execute $src "riscv_apex_lto"
        }
    }

    lto_finish
}
